export const MARKETS = ['Global', 'United States', 'India', 'United Kingdom', 'China', 'Japan'];

export const STOCK_DATA = {
  Global: [
    { symbol: 'TSLA',  name: 'Tesla Inc.',       sector: 'EV' },
    { symbol: 'AAPL',  name: 'Apple Inc.',        sector: 'Technology' },
    { symbol: 'NVDA',  name: 'NVIDIA Corp.',       sector: 'Semiconductors' },
    { symbol: 'MSFT',  name: 'Microsoft Corp.',    sector: 'Software' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.',      sector: 'Internet' },
    { symbol: 'AMZN',  name: 'Amazon.com',         sector: 'E-commerce' },
    { symbol: 'META',  name: 'Meta Platforms',     sector: 'Social Media' },
    { symbol: 'AMD',   name: 'AMD Inc.',           sector: 'Semiconductors' },
  ],
  'United States': [
    { symbol: 'TSLA', name: 'Tesla Inc.',       sector: 'EV' },
    { symbol: 'AAPL', name: 'Apple Inc.',        sector: 'Technology' },
    { symbol: 'NVDA', name: 'NVIDIA Corp.',       sector: 'Semiconductors' },
    { symbol: 'MSFT', name: 'Microsoft Corp.',    sector: 'Software' },
    { symbol: 'JPM',  name: 'JPMorgan Chase',     sector: 'Banking' },
    { symbol: 'V',    name: 'Visa Inc.',          sector: 'Payments' },
    { symbol: 'WMT',  name: 'Walmart Inc.',       sector: 'Retail' },
    { symbol: 'DIS',  name: 'Walt Disney',        sector: 'Entertainment' },
  ],
  India: [
    { symbol: 'RELIANCE.NS',   name: 'Reliance Industries', sector: 'Conglomerate' },
    { symbol: 'TCS.NS',        name: 'Tata Consultancy',    sector: 'IT Services' },
    { symbol: 'INFY',          name: 'Infosys Ltd.',         sector: 'IT Services' },
    { symbol: 'HDFCBANK.NS',   name: 'HDFC Bank',            sector: 'Banking' },
    { symbol: 'TATAMOTORS.NS', name: 'Tata Motors',          sector: 'Automotive' },
    { symbol: 'WIPRO',         name: 'Wipro Ltd.',           sector: 'IT Services' },
    { symbol: 'ITC.NS',        name: 'ITC Limited',          sector: 'FMCG' },
    { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel',        sector: 'Telecom' },
  ],
  'United Kingdom': [
    { symbol: 'HSBA.L', name: 'HSBC Holdings', sector: 'Banking' },
    { symbol: 'AZN',    name: 'AstraZeneca',   sector: 'Pharma' },
    { symbol: 'BP',     name: 'BP plc',        sector: 'Energy' },
    { symbol: 'SHEL',   name: 'Shell plc',     sector: 'Energy' },
    { symbol: 'ULVR.L', name: 'Unilever',      sector: 'Consumer' },
    { symbol: 'GSK',    name: 'GSK plc',       sector: 'Pharma' },
    { symbol: 'RIO',    name: 'Rio Tinto',     sector: 'Mining' },
    { symbol: 'BARC.L', name: 'Barclays',      sector: 'Banking' },
  ],
  China: [
    { symbol: 'BABA',  name: 'Alibaba Group',   sector: 'E-commerce' },
    { symbol: 'BIDU',  name: 'Baidu Inc.',       sector: 'Internet' },
    { symbol: 'JD',    name: 'JD.com Inc.',      sector: 'E-commerce' },
    { symbol: 'NIO',   name: 'NIO Inc.',         sector: 'EV' },
    { symbol: 'PDD',   name: 'Pinduoduo',        sector: 'E-commerce' },
    { symbol: 'TCEHY', name: 'Tencent Holdings', sector: 'Internet' },
    { symbol: 'LI',    name: 'Li Auto',          sector: 'EV' },
    { symbol: 'XPEV',  name: 'XPeng Inc.',       sector: 'EV' },
  ],
  Japan: [
    { symbol: 'SONY',  name: 'Sony Group',      sector: 'Electronics' },
    { symbol: 'TM',    name: 'Toyota Motor',    sector: 'Automotive' },
    { symbol: 'NTDOY', name: 'Nintendo',        sector: 'Gaming' },
    { symbol: 'HMC',   name: 'Honda Motor',     sector: 'Automotive' },
    { symbol: 'MUFG',  name: 'Mitsubishi UFJ',  sector: 'Banking' },
    { symbol: 'SMFG',  name: 'Sumitomo Mitsui', sector: 'Banking' },
  ],
};
